stages:
  data_split:
    cmd: python src/data/split_data.py
    deps:
      - data/raw/raw.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  normalize:
    cmd: python src/models/normalize.py
    deps:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
    outs:
      - data/processed/X_train_scaled.csv
      - data/processed/X_test_scaled.csv
      - data/processed/scaler.pkl
  train:
    cmd: python src/models/train_model.py
    deps:
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv

  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
      - models/final_model.pkl
      - data/processed/X_test_scaled.csv
      - data/processed/y_test.csv
