stages:

  data_split:

    cmd: python src/data/split_data.py

    deps:

      - data/raw/raw.csv

    outs:

      - data/processed/X_train.csv

      - data/processed/X_test.csv

      - data/processed/y_train.csv

      - data/processed/y_test.csv

      

  normalize:

    cmd: python src/models/normalize.py

    deps:

      - data/processed/X_train.csv

      - data/processed/X_test.csv

    outs:

      - data/processed/X_train_scaled.csv

      - data/processed/X_test_scaled.csv

      - data/processed/scaler.pkl

      

  grid_search:

    cmd: python src/models/grid_search.py

    deps:

      - data/processed/X_train_scaled.csv

      - data/processed/y_train.csv

    outs:

      - models/grid_search_results.json

      - models/Lasso_best_model.pkl

      - models/Ridge_best_model.pkl

      - models/RandomForest_best_model.pkl

      

  train:

    cmd: python src/models/train_model.py

    deps:

      - data/processed/X_train_scaled.csv

      - data/processed/y_train.csv

      - models/grid_search_results.json

    outs:

      - models/final_model.pkl

      - models/train_metrics.json

      

  evaluate:

    cmd: python src/models/evaluate_model.py

    deps:

      - models/final_model.pkl

      - data/processed/X_test_scaled.csv

      - data/processed/y_test.csv

    outs:

      - metrics/evaluation_metrics.json

      - metrics/predictions.csv
